### ISSUE TITLE
run anomaly_detection.py

### ISSUE THREAD

**Issue by yixiyixi5** [tSchlegl/f-AnoGAN#14]
[*] Reading checkpoints...
Traceback (most recent call last):
  File "anomaly_detection.py", line 285, in <module>
    anomaly_scoring("z_encoding_d/izi_tanh_fc/wganTrain-iter7/wgangp_64_normal_crIt5_2020-06-30-0926-enc_iter50000_2020-06-30-1424/z_encoding_izif-MSE-k1.00_tanh_fc/checkpoints", 200)
  File "anomaly_detection.py", line 238, in anomaly_scoring
    assert isLoaded
AssertionError

**Comment by yixiyixi5** [comment]
help me
