### ISSUE TITLE
Issue in  image path;Can you help me

### ISSUE THREAD

**Issue by adeebakausar** [tSchlegl/f-AnoGAN#5]
Traceback (most recent call last):
  File "wgangp_64x64.py", line 444, in <module>
    train()
  File "wgangp_64x64.py", line 340, in train
    _x = inf_train_gen().next()
  File "wgangp_64x64.py", line 336, in inf_train_gen
    for (images,) in train_gen():
  File "/content/f-AnoGAN/tflib/img_loader.py", line 76, in get_epoch
    assert(len(files) > 0)
AssertionError

**Comment by adeebakausar** [comment]
Please share your few images of your dataset, So  that i feel easy  to run this  repo

**Comment by lzzlxxlsz** [comment]
hello,have you run the code sucessfully?

**Comment by murielmazzetto** [comment]
I had this problem, it occurred because my image files were .jpeg, and the code is set to run with .png.
I converted my files using mogrify -format png *.jpeg on ubuntu 18.04 and it was solved.

**Comment by lzzlxxlsz** [comment]
What's the result? Can anomalous data be identified?

**Comment by philipwelia** [comment]
I met the issue as well, and I had renamed my filename to .png, but it didnt work . had anyone solve this problem?
